### ISSUE TITLE
Tailwind injectPosition settings being ignored.

### ISSUE THREAD

**Issue by binaryartifex** [nuxt-modules/tailwindcss#916]
I have to fetch some configuration data for a white label app before the app loads on the client. im doing this via a plugin. however any attempts between both the tailwind module configs and the useHead configs as far as ordering is concerned seems to be completely ignored. Ive switched and swapped the tag and injectPosition configs ad-nauseum with no change.

How can i force inline declared styles to come after tailwind so i can override default css variables??

```typescript
// plugins/client-profile.ts
export default defineNuxtPlugin({
  name: "clientProfile",
  async setup() {
    useHead({
      style: [
        {
          innerHTML: `:root {--foobar: #ff0000;}`,
        },
        {
          tagPriority: "critical",
          tagPosition: "head",
        },
      ],
    });
  },
});
```
```css
/* assets/styles/tailwind.css */
@import "tailwindcss/base";
@layer base {
  :root {
    --foobar: theme(colors.violet.600);
  }
}
```
```typescript
// nuxt.config.ts
{
  tailwindcss: {
    cssPath: ["~/assets/css/tailwind.css", { injectPosition: "first" }],
  },
}
```
![Image](https://github.com/user-attachments/assets/f50dc262-6e1c-464e-ae02-6aaaf4933da5)
